baseURL = "https://bridgetkromhout.com/"
languageCode = "en-us"
title = "Bridget Kromhout"
theme = "gohugo-theme-ananke"
background_image = "/images/kitties.png"

# Menu

[[menu.main]]
  Name = "Blog"
  URL = "/blog/"
  weight = -40

[[menu.main]]
  Name = "Speaking"
  URL = "/speaking/"
  weight = -30

[[menu.main]]
  Name = "Writing"
  URL = "/writing/"
  weight = -20

[[menu.main]]
  Name = "Podcasts"
  URL = "/podcasts/"
  weight = -15

[[menu.main]]
  Name = "Reviews"
  URL = "/reviews/"
  weight = -10

[[menu.main]]
  Name = "Contact"
  URL = "/contact/"
  weight = -1


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Bridget Kromhout"
  twitter = "https://twitter.com/bridgetkromhout"
  background_color_class = "bg-white"
  featured_image = "/images/kitties.png"
